on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.6
          target: esp32-s3
          path: '.'
      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: ${GITHUB_WORKSPACE}/build/output-file.bin
